# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
android.enableJetifier=true
android.useAndroidX=true
org.gradle.jvmargs=-Xmx1536m
android.nonFinalResIds=false
org.gradle.java.home=/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home
#org.gradle.jvmargs=-Xmx4608m
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true
BAZAAR_IAB_PUBLIC_KEY=MIHNMA0GCSqGSIb3DQEBAQUAA4G7ADCBtwKBrwDO8XO7cKWD0kYFYQiEn8W2CLQYDOUeG+eDxwcnoTgySTj7aXylrrZ2NZ4055frMGVVA0kO6FlN1OUsJCavjC70Vq43fP3Tt+1naa2g9Hno+/LIB+xmoNyZx1Lh4OHB1dJLHVz2dO3v0oF2wrU2h8IvwapHQDjzHelhtNHqqarZ4anZq8oXBNPmMXb/bVUhnrd1N0UmotLAfFztn+qVH7JWLtr2M1ap+VItcGk5LDECAwEAAQ==
MYKET_IAB_PUBLIC_KEY=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDNNdpgF833beZt1Pz9gfrlBHNXk+QqKaD8qeT2K4sXs6PVMHxW8V8UfqN0GfSC8iPnc6oaiNWminpqECfJkpJKwrxN6DdnUm6cAN9yMveEbw/j6PyoAJEPmgKw5M6q8zxxevMRJTfrYsNcIclu2aszF5GGB8059trHTcF8PT+GvwIDAQAB